//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER_TO_Q
    {
        public int S_ID { get; set; }
        public int Q_NUM { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> POINTS { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}
