//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_RELATED_FIELD
    {
        public int POS_ID { get; set; }
        public string FIELD_NAME { get; set; }
    
        public virtual FIELD FIELD { get; set; }
        public virtual WANTED_POS WANTED_POS { get; set; }
    }
}
