//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESUME()
        {
            this.DOWNLOAD_RESUME = new HashSet<DOWNLOAD_RESUME>();
        }
    
        public int S_ID { get; set; }
        public string OCCUPATION { get; set; }
        public string DOC_PATH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOWNLOAD_RESUME> DOWNLOAD_RESUME { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
