//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VONE
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.ANSWER_TO_Q = new HashSet<ANSWER_TO_Q>();
            this.RESUME = new HashSet<RESUME>();
        }
    
        public int S_ID { get; set; }
        public string NAME { get; set; }
        public string COLLEGE_NAME { get; set; }
        public string MAJOR { get; set; }
        public string DEGREE { get; set; }
        public Nullable<System.DateTime> ADMITTED_YEAR { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> PHONE_NUM { get; set; }
        public string S_KEY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWER_TO_Q> ANSWER_TO_Q { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESUME> RESUME { get; set; }
    }
}
